/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from '@angular/common';
import * as import2 from '../../../../build/components/paging/paging.component';
import * as import3 from './pager.component.ngfactory';
import * as import4 from '../../../../build/components/paging/pager.component';
const styles_DataTablePagingComponent:any[] = ([] as any[]);
export const RenderType_DataTablePagingComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_DataTablePagingComponent,
  data: {}
}
);
export function View_DataTablePagingComponent_0():import0.ɵViewDefinition {
  return import0.ɵvid(2,[
    import0.ɵqud(201326592,1,{pager: 0}),
    import0.ɵted((null as any),['\n    ']),
      import0.ɵeld(0,(null as any),(null as any),7,'div',([] as any[]),[[
        2,
        'height',
        'px'
      ]
    ],(null as any),(null as any),(null as any),(null as any)),
    import0.ɵdid(139264,(null as any),0,import1.NgClass,[
      import0.IterableDiffers,
      import0.KeyValueDiffers,
      import0.ElementRef,
      import0.Renderer
    ]
      ,{ngClass: [
        0,
        'ngClass'
      ]
    },(null as any)),
    import0.ɵpod(['selected-count']),
    import0.ɵted((null as any),['\n      ']),
      import0.ɵeld(0,(null as any),(null as any),2,'datatable-pager',[[
        'class',
        'datatable-pager'
      ]
      ],[[
        3,
        'hidden',
        0
      ]
      ],[[
        (null as any),
        'change'
      ]
    ],(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:import2.DataTablePagingComponent = view.component;
      if (('change' === eventName)) {
        const pd_0:any = ((<any>comp.page.emit($event)) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      return allowDefault;
    },import3.View_DataTablePagerComponent_0,import3.RenderType_DataTablePagerComponent),
    import0.ɵdid(24576,[
      [
        1,
        4
      ]
      ,
      [
        'pager',
        4
      ]

    ]
    ,0,import4.DataTablePagerComponent,([] as any[]),{
      pagerLeftArrowIcon: [
        0,
        'pagerLeftArrowIcon'
      ]
      ,
      pagerRightArrowIcon: [
        1,
        'pagerRightArrowIcon'
      ]
      ,
      pagerPreviousIcon: [
        2,
        'pagerPreviousIcon'
      ]
      ,
      pagerNextIcon: [
        3,
        'pagerNextIcon'
      ]
      ,
      size: [
        4,
        'size'
      ]
      ,
      count: [
        5,
        'count'
      ]
      ,
      page: [
        6,
        'page'
      ]

    }
    ,{change: 'change'}),
    import0.ɵted((null as any),['\n      ']),
    import0.ɵted((null as any),['\n    ']),
    import0.ɵted((null as any),['\n  '])
  ]
  ,(check,view) => {
    var comp:import2.DataTablePagingComponent = view.component;
    const currVal_0:any = check(view,4,0,comp.selectedMessage);
    check(view,3,0,currVal_0);
    const currVal_1:any = comp.pagerLeftArrowIcon;
    const currVal_2:any = comp.pagerRightArrowIcon;
    const currVal_3:any = comp.pagerPreviousIcon;
    const currVal_4:any = comp.pagerNextIcon;
    const currVal_5:any = comp.pageSize;
    const currVal_6:any = comp.rowCount;
    const currVal_7:any = comp.curPage;
    check(view,7,0,currVal_1,currVal_2,currVal_3,currVal_4,currVal_5,currVal_6,currVal_7);
  },(check,view) => {
    var comp:import2.DataTablePagingComponent = view.component;
    const currVal_0:any = comp.pagingHeight;
    check(view,2,0,currVal_0);
    const currVal_1:boolean = !comp.isVisible;
    check(view,6,0,currVal_1);
  });
}
const RenderType_DataTablePagingComponent_Host:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {}
}
);
function View_DataTablePagingComponent_Host_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[
      import0.ɵeld(0,(null as any),(null as any),1,'datatable-paging',[[
        'class',
        'datatable-paging'
      ]
    ],(null as any),(null as any),(null as any),View_DataTablePagingComponent_0,RenderType_DataTablePagingComponent),
    import0.ɵdid(24576,(null as any),0,import2.DataTablePagingComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const DataTablePagingComponentNgFactory:import0.ComponentFactory<import2.DataTablePagingComponent> = import0.ɵccf('datatable-paging',import2.DataTablePagingComponent,View_DataTablePagingComponent_Host_0);