/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from '@angular/common';
import * as import2 from '../../../../build/components/legend/legend.component';
const styles_DataTableLegendComponent:any[] = ([] as any[]);
export const RenderType_DataTableLegendComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_DataTableLegendComponent,
  data: {}
}
);
function View_DataTableLegendComponent_1():import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵeld(0,(null as any),(null as any),5,'li',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵted((null as any),['\n                ']),
    import0.ɵeld(0,(null as any),(null as any),2,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
      import0.ɵeld(0,(null as any),(null as any),0,'i',([] as any[]),[[
        3,
        'className',
        0
      ]
    ],(null as any),(null as any),(null as any),(null as any)),
    import0.ɵted((null as any),[
      '',
      ''
    ]
    ),
    import0.ɵted((null as any),['\n            '])
  ]
  ,(null as any),(check,view) => {
    var comp:any = view.component;
    const currVal_0:any = view.context.$implicit.styles;
    check(view,3,0,currVal_0);
    const currVal_1:any = view.context.$implicit.name;
    check(view,4,0,currVal_1);
  });
}
export function View_DataTableLegendComponent_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵted((null as any),['\n    ']),
    import0.ɵeld(0,(null as any),(null as any),7,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵted((null as any),['\n        ']),
    import0.ɵeld(0,(null as any),(null as any),4,'ul',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵted((null as any),['\n            ']),
    import0.ɵand(8388608,(null as any),(null as any),1,(null as any),View_DataTableLegendComponent_1),
    import0.ɵdid(401408,(null as any),0,import1.NgForOf,[
      import0.ViewContainerRef,
      import0.TemplateRef,
      import0.IterableDiffers
    ]
      ,{ngForOf: [
        0,
        'ngForOf'
      ]
    },(null as any)),
    import0.ɵted((null as any),['\n        ']),
    import0.ɵted((null as any),['\n    ']),
    import0.ɵted((null as any),['\n    '])
  ]
  ,(check,view) => {
    var comp:import2.DataTableLegendComponent = view.component;
    const currVal_0:any = comp.legends;
    check(view,6,0,currVal_0);
  },(null as any));
}
const RenderType_DataTableLegendComponent_Host:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {}
}
);
function View_DataTableLegendComponent_Host_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[
      import0.ɵeld(0,(null as any),(null as any),1,'datatable-legend',[[
        'class',
        'datatable-legend'
      ]
    ],(null as any),(null as any),(null as any),View_DataTableLegendComponent_0,RenderType_DataTableLegendComponent),
    import0.ɵdid(24576,(null as any),0,import2.DataTableLegendComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const DataTableLegendComponentNgFactory:import0.ComponentFactory<import2.DataTableLegendComponent> = import0.ɵccf('datatable-legend',import2.DataTableLegendComponent,View_DataTableLegendComponent_Host_0);